server:
  port: 8080

spring:
  application: 
    name: customer
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/customer
    driver-class: com.mysql.cj.jdbc.MySQL5Dialect
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true