server:
  port: 8081

spring:
  application: 
    name: customer
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/customer
    driver-class: com.mysql.cj.jdbc.MySQL5Dialect
  jpa:
    hibernate:
      ddl-auto: update