version: "3.8"

services:
  customer:
    image: mysql:8
    container_name: customer
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${CUSTOMER_DB}
    volumes:
      - mysql_customer:/var/lib/mysql
    ports:
      - "${CUSTOMER_PORT}:3306"
  
  fraud:
    image: postgres
    container_name: fraud
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${FRAUD_DB}
    volumes:
      - postgres_fraud:/data/postgres
    ports:
      - "${FRAUD_PORT}:5432"
    
  notification:
    image: mysql:8
    container_name: notification
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NOTIFICATION_DB}
    volumes:
      - mysql_notification:/var/lib/mysql
    ports:
      - "${NOTIFICATION_PORT}:3306"
  
volumes:
  mysql_customer:
  postgres_fraud:
  mysql_notification:
