version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer
    volumes:
      - app:/var/lib/mysql
    ports:
      - "3306:3306"
  
volumes:
  app:
# version: "3.8"

# services:
#   mysqldb:
#     image: mysql:5.7
#     restart: unless-stopped
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=root
#       - MYSQL_DATABASE=customer
#     ports:
#       - 3306:3306
#     volumes:
#       - db:/var/lib/mysql
#   app:
#     depends_on:
#       - mysqldb
#     build: ./microservices
#     restart: on-failure
#     env_file: ./.env
#     ports:
#       - 8080:8080
#     environment:
#       SPRING_APPLICATION_JSON: '{
#         "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/customer?useSSL=false",
#         "spring.datasource.username" : "root",
#         "spring.datasource.password" : "root",
#         "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#         "spring.jpa.hibernate.ddl-auto" : "update"
#       }'
#     stdin_open: true
#     tty: true

# volumes:
#   db: