server:
  port: 8081

spring:
  application: 
    name: fraud
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:54321/fraud
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always